#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "ojs"
name = "OJS"
description.en = "Software to manage scholarly journals"
description.fr = "Logiciel pour gérer des revues scientifiques"

version = "3.4.0-8~ynh2"

maintainers = ["DeMiro5001"]

[upstream]
license = "GPL-3.0-only"
website = "https://pkp.sfu.ca/software/ojs"
admindoc = "https://docs.pkp.sfu.ca/admin-guide/"
userdoc = "https://docs.pkp.sfu.ca/"
code = "https://github.com/pkp/ojs"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "150M"
ram.build = "50M"
ram.runtime = "50M"

[install]

    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices.en = "en"
    choices.fr_FR = "fr"
    default = "en"

    [install.locale]
    ask.en = "Choose the application locale"
    ask.fr = "Choisissez les paramètres régionaux de l'application"
    type = "select"
    choices.en = "en"
    choices.fr_FR = "fr"
    default = "en"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

    [install.mail_user]
    default = "noreply"
    type = "select"
    choices.noreply="noreply"
    choices.contact="contact"
    ask.en = "This is the email that will be used by the app to send system notifications"
    help.en = "OJS will send emails using the sender mail_user@domain."
    ask.fr = "Il s'agit de l'e-mail qui sera utilisé par l'application pour envoyer des notifications système"
    help.fr = "OJS enverra des e-mails en utilisant l'expéditeur mail_user@domain."

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://pkp.sfu.ca/ojs/download/ojs-3.5.0-0.tar.gz"
    sha256 = "3ea48045ccc1995108cc28d4a9df6ee6d2bbdfd3726cf91a599a53c0d268635a"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server, php8.4-mysqli, php8.4-mbstring, php8.4-xml, php8.4-intl, php8.4-bcmath, php8.4-curl, php8.4-gd, php8.4-zip, poppler-utils, antiword, python3-venv"

    [resources.database]
    type = "mysql"
