#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "ojs"
name = "OJS"

description.en = "Software to manage scholarly journals"
description.fr = "Logiciel pour gérer des revues scientifiques"

version = "3.4.0-7~ynh1"

maintainers = ["DeMiro5001"]

[upstream]
license = "GPL-3.0-only"
website = "https://pkp.sfu.ca/software/ojs"
admindoc = "https://docs.pkp.sfu.ca/admin-guide/"
userdoc = "https://docs.pkp.sfu.ca/"
code = "https://github.com/pkp/ojs"

[integration]

yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = true
ldap = false

sso = false

disk = "150M"
ram.build = "50M"
ram.runtime = "50M"

[install]

    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/ojs"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["fr_FR", "en_GB"]
    default = "fr_FR"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://pkp.sfu.ca/ojs/download/ojs-3.4.0-7.tar.gz"
    sha256 = "f330fdbbed8900e4510484dc1a66085f3da79ba96cbe38894d0b238b3e80733a"

    #autoupdate.strategy = "latest_github_tag"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server, php8.3-mysqli, php8.3-mbstring, php8.3-xml, php8.3-intl"

    [resources.database]
    type = "mysql"
