#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "ojs"
name = "OJS"
description.en = "Software to manage scholarly journals"
description.fr = "Logiciel pour gérer des revues scientifiques"

version = "3.4.0-8~ynh2"

maintainers = ["DeMiro5001"]

[upstream]
license = "GPL-3.0-only"
website = "https://pkp.sfu.ca/software/ojs"
admindoc = "https://docs.pkp.sfu.ca/admin-guide/"
userdoc = "https://docs.pkp.sfu.ca/"
code = "https://github.com/pkp/ojs"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "150M"
ram.build = "50M"
ram.runtime = "50M"

[install]

    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices.sq = "Albanian"
    choices.hy = "Armenian"
    choices.az = "Azerbaijani"
    choices.id = "Bahasa Indonesia"
    choices.bs = "Bosnian"
    choices.ca = "Català"
    choices.zh_Hans = "Chinese"
    choices.zh_Hant = "Chinese"
    choices.da = "Dansk"
    choices.de = "Deutsch"
    choices.en = "English"
    choices.es = "Español"
    choices.es_MX = "Español (México)"
    choices.eo = "Esperanto"
    choices.eu = "Euskara"
    choices.fr_CA = "Français (Canada)"
    choices.fr_FR = "Français (France)"
    choices.gl = "Galego"
    choices.ka = "Georgian"
    choices.hr = "Hrvatski"
    choices.it = "Italiano"
    choices.kk = "Kazakh"
    choices.ky = "Kirghiz"
    choices.lv = "Latviešu"
    choices.lt = "Lietuvių"
    choices.hu = "Magyar"
    choices.ms = "Malay"
    choices.el = "Modern Greek"
    choices.nl = "Nederlands"
    choices.se = "Northern Sami"
    choices.nb = "Norwegian Bokmål"
    choices.pl = "Polski"
    choices.pt_BR = "Português (Brasil)"
    choices.pt_PT = "Português (Portugal)"
    choices.ro = "Română"
    choices.gd = "Scottish Gaelic"
    choices.si = "Sinhala"
    choices.sk = "Slovenský"
    choices.sl = "Slovenščina"
    choices.fi = "Suomi"
    choices.sv = "Svenska"
    choices.sw = "Swahili"
    choices.tl = "Tagalog"
    choices.vi = "Tiếng Việt"
    choices.tr = "Türkçe"
    choices.ur = "Urdu"
    choices.uz = "Uzbek"
    choices.is = "Íslenska"
    choices.cs = "Čeština"
    choices.bg = "Български"
    choices.mk = "Македонски"
    choices.mn = "Монгол"
    choices.ru = "Русский"
    choices.sr = "Српски"
    choices.uk = "Українська"
    choices.he = "עברית"
    choices.ar = "العربية"
    choices.fa = "فارسی"
    choices.mr = "मराठी"
    choices.hi = "हिंदी"
    choices.th = "ไทย"
    choices.zh_CN = "中文 (中国)"
    choices.ja = "日本語"
    choices.ja_JP = "日本語 (日本)"
    choices.ko = "한국어"
    default = "en"

    [install.locale]
    ask.en = "Choose the application locale"
    ask.fr = "Choisissez les paramètres régionaux de l'application"
    type = "select"
    choices.ar="Arabic (ar)"
    choices.az="Azerbaijani (az)"
    choices.bg="Bulgarian (bg)"
    choices.bs="Bosnian (bs)"
    choices.ca="Catalan (ca)"
    choices.cs="Czech (cs)"
    choices.da="Danish (da)"
    choices.de="German (de)"
    choices.el="Modern Greek (el)"
    choices.en="English (en)"
    choices.eo="Esperanto (eo)"
    choices.es="Spanish (es)"
    choices.es_MX="Spanish (Mexico) (es_MX)"
    choices.eu="Basque (eu)"
    choices.fa="Persian (fa)"
    choices.fi="Finnish (fi)"
    choices.fr_CA="French (Canada) (fr_CA)"
    choices.fr_FR="French (France) (fr_FR)"
    choices.gd="Scottish Gaelic (gd)"
    choices.gl="Galician (gl)"
    choices.he="Hebrew (he)"
    choices.hi="Hindi (hi)"
    choices.hr="Croatian (hr)"
    choices.hu="Hungarian (hu)"
    choices.hy="Armenian (hy)"
    choices.id="Indonesian (id)"
    choices.is="Icelandic (is)"
    choices.it="Italian (it)"
    choices.ja="Japanese (ja)"
    choices.ja_JP="Japanese (Japan) (ja_JP)"
    choices.ka="Georgian (ka)"
    choices.kk="Kazakh (kk)"
    choices.ko="Korean (ko)"
    choices.ky="Kirghiz (ky)"
    choices.lt="Lithuanian (lt)"
    choices.lv="Latvian (lv)"
    choices.mk="Macedonian (mk)"
    choices.mn="Mongolian (mn)"
    choices.mr="Marathi (mr)"
    choices.ms="Malay (ms)"
    choices.nb="Norwegian Bokmål (nb)"
    choices.nl="Dutch (nl)"
    choices.pl="Polish (pl)"
    choices.pt_BR="Portuguese (Brazil) (pt_BR)"
    choices.pt_PT="Portuguese (Portugal) (pt_PT)"
    choices.ro="Romanian (ro)"
    choices.ru="Russian (ru)"
    choices.se="Northern Sami (se)"
    choices.si="Sinhala (si)"
    choices.sk="Slovak (sk)"
    choices.sl="Slovenian (sl)"
    choices.sq="Albanian (sq)"
    choices.sr="Serbian (sr)"
    choices.sv="Swedish (sv)"
    choices.sw="Swahili (sw)"
    choices.th="Thai (th)"
    choices.tl="Tagalog (tl)"
    choices.tr="Turkish (tr)"
    choices.uk="Ukrainian (uk)"
    choices.ur="Urdu (ur)"
    choices.uz="Uzbek (uz)"
    choices.vi="Vietnamese (vi)"
    choices.zh_CN="Chinese (China) (zh_CN)"
    choices.zh_Hans="Chinese (zh_Hans)"
    choices.zh_Hant="Chinese (zh_Hant)"
    default = "en"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://pkp.sfu.ca/ojs/download/ojs-3.5.0-0.tar.gz"
    sha256 = "3ea48045ccc1995108cc28d4a9df6ee6d2bbdfd3726cf91a599a53c0d268635a"

    [resources.system_user]
    allow_email = true
    mail_user = "noreply"

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server, php8.4-mysqli, php8.4-mbstring, php8.4-xml, php8.4-intl, php8.4-bcmath, php8.4-curl, php8.4-gd, php8.4-zip, poppler-utils, antiword, python3-venv"

    [resources.database]
    type = "mysql"
