#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "ojs"
name = "OJS"

description.en = "Software to manage scholarly journals"
description.fr = "Logiciel pour gérer des revues scientifiques"

version = "3.4.0-7~ynh2"

maintainers = ["DeMiro5001"]

[upstream]
license = "GPL-3.0-only"
website = "https://pkp.sfu.ca/software/ojs"
admindoc = "https://docs.pkp.sfu.ca/admin-guide/"
userdoc = "https://docs.pkp.sfu.ca/"
code = "https://github.com/pkp/ojs"

[integration]

yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = true
ldap = false

sso = false

disk = "150M"
ram.build = "50M"
ram.runtime = "50M"

[install]

    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/ojs"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["Français", "English"]
    default = "Français"

    [install.locale]
    ask.en = "Choose the application locale"
    ask.fr = "Choisissez les paramètres régionaux de l'application"
    type = "select"
    choices.sq = "Albanian"
    choices.hy = "Armenian"
    choices.az = "Azerbaijani"
    choices.id = "Bahasa Indonesia"
    choices.bs = "Bosnian"
    choices.ca = "Català"
    choices.zh_Hans = "Chinese"
    choices.zh_Hant = "Chinese"
    choices.da = "Dansk"
    choices.de = "Deutsch"
    choices.en = "English"
    choices.es = "Español"
    choices.es_MX = "Español (México)"
    choices.eo = "Esperanto"
    choices.eu = "Euskara"
    choices.fr_CA = "Français (Canada)"
    choices.fr_FR = "Français (France)"
    choices.gl = "Galego"
    choices.ka = "Georgian"
    choices.hr = "Hrvatski"
    choices.it = "Italiano"
    choices.kk = "Kazakh"
    choices.ky = "Kirghiz"
    choices.lv = "Latviešu"
    choices.lt = "Lietuvių"
    choices.hu = "Magyar"
    choices.ms = "Malay"
    choices.el = "Modern Greek"
    choices.nl = "Nederlands"
    choices.se = "Northern Sami"
    choices.nb = "Norwegian Bokmål"
    choices.pl = "Polski"
    choices.pt_BR = "Português (Brasil)"
    choices.pt_PT = "Português (Portugal)"
    choices.ro = "Română"
    choices.gd = "Scottish Gaelic"
    choices.si = "Sinhala"
    choices.sk = "Slovenský"
    choices.sl = "Slovenščina"
    choices.sr@latin = "Srpski"
    choices.fi = "Suomi"
    choices.sv = "Svenska"
    choices.sw = "Swahili"
    choices.tl = "Tagalog"
    choices.vi = "Tiếng Việt"
    choices.tr = "Türkçe"
    choices.ur = "Urdu"
    choices.uz = "Uzbek"
    choices.uz@cyrillic = "Uzbek"
    choices.uz@latin = "Uzbek"
    choices.is = "Íslenska"
    choices.cs = "Čeština"
    choices.be@cyrillic = "Беларуская"
    choices.bg = "Български"
    choices.mk = "Македонски"
    choices.mn = "Монгол"
    choices.ru = "Русский"
    choices.sr = "Српски"
    choices.sr@cyrillic = "Српски"
    choices.uk = "Українська"
    choices.he = "עברית"
    choices.ar = "العربية"
    choices.fa = "فارسی"
    choices.mr = "मराठी"
    choices.hi = "हिंदी"
    choices.th = "ไทย"
    choices.zh_CN = "中文 (中国)"
    choices.ja = "日本語"
    choices.ja_JP = "日本語 (日本)"
    choices.ko = "한국어"
default = "en"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://pkp.sfu.ca/ojs/download/ojs-3.4.0-7.tar.gz"
    sha256 = "f330fdbbed8900e4510484dc1a66085f3da79ba96cbe38894d0b238b3e80733a"

    #autoupdate.strategy = "latest_github_tag"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server, php8.3, php8.3-mysqli, php8.3-mbstring, php8.3-xml, php8.3-intl"

    [resources.database]
    type = "mysql"
