#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "ojs"
name = "OJS"

description.en = "Open Journal Systems is open source software to manage scholarly journals"
description.fr = "Open Journal Systems est un logiciel open source pour gérer des revues scientifiques"

version = "3.4.0-7~ynh1"

maintainers = ["DeMiro5001"]

[upstream]
license = "GPL-3.0-only"
website = "https://pkp.sfu.ca/software/ojs"

admindoc = "https://docs.pkp.sfu.ca/admin-guide/"
userdoc = "https://docs.pkp.sfu.ca/"
code = "https://github.com/pkp/ojs"

[integration]
yunohost = ">= 11.2.29"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "150M"
ram.build = "50M"
ram.runtime = "50M"

[install]

    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/ojs"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/pkp/ojs/archive/refs/tags/3_4_0-7.tar.gz"
        sha256 = "f0e22eec0f52ca720492b817dc596601e68939bd7e26a2da83348fca5f1daf04"

        autoupdate.strategy = "latest_github_tag"

        [resources.sources.pkp]
        url = "https://github.com/pkp/pkp-lib/archive/refs/tags/3_4_0-7.tar.gz"
        sha256 = "0b95485d91d7a0e1c3cf85b76a57d681a7f35ffc2c11ceb0a922ae05efe5e3b0"
        autoupdate.strategy = "latest_github_tag"

        [resources.sources.customBlockManager]
        url = "https://github.com/pkp/customBlockManager/archive/refs/tags/3_4_0-7.tar.gz"
        sha256 = "c4f270d9737698da79d28f601f8c93e14d8c667feeba6ba60d40dbbd620d96d1"
        autoupdate.strategy = "latest_github_tag"

        [resources.sources.staticPages]
        url = "https://github.com/pkp/staticPages/archive/refs/tags/3_4_0-7.tar.gz"
        sha256 = "b4d0371233f20bf619ff83e5aff050ce387bd24c89aaec23a438fd5e9661015e"
        autoupdate.strategy = "latest_github_tag"

        [resources.sources.tinymce]
        url = "https://github.com/pkp/tinymce/archive/refs/tags/3_4_0-7.tar.gz"
        sha256 = "90e22e4b50e240287a767b6d9e62b959f423e3acfeba60cee72ad2a7ba6d72d3"
        autoupdate.strategy = "latest_github_tag"

        [resources.sources.pdfJsViewer]
        url = "https://github.com/pkp/pdfJsViewer/archive/refs/tags/3_4_0-7.tar.gz"
        sha256 = "2efbfeb490b5c7ff696df99c423ef44e5e02468114f0f5bd61764cf88eb4f390"
        autoupdate.strategy = "latest_github_tag"

        [resources.sources.manual]
        url = "https://github.com/pkp/ojs-user-guide/archive/refs/tags/3_4_0rc1.tar.gz"
        sha256 = "49c8fafe8483b28afe0cea54f8910f05b412d4e4467c48125daf5df5aa7e5f7f"
        autoupdate.strategy = "latest_github_tag"

        [resources.sources.lensGalley]
        url = "https://github.com/asmecher/lensGalley/archive/refs/tags/3_4_0-7.tar.gz"
        sha256 = "f1d29ccdd03a21a99262837af8f05981c22086a74714faacc63071320957e2b2"
        autoupdate.strategy = "latest_github_tag"

        [resources.sources.googleAnalytics]
        url = "https://github.com/pkp/googleAnalytics/archive/refs/tags/3_4_0-7.tar.gz"
        sha256 = "a2ee03b252d8a407db235fb7255305c7d3088e95e8eea2cfae8c85264d7670e5"
        autoupdate.strategy = "latest_github_tag"

        [resources.sources.makeSubmission]
        url = "https://github.com/pkp/makeSubmission/archive/refs/tags/3_4_0-7.tar.gz"
        sha256 = "bbffaa203d1633e840e55ea8dc29c660b4365a8312d7ccb51b3ac472a6a0852e"
        autoupdate.strategy = "latest_github_tag"

        [resources.sources.reviewReport]
        url = "https://github.com/pkp/reviewReport/archive/refs/tags/3_4_0-7.tar.gz"
        sha256 = "f80f70046db55076132531723a45c1a12e2bd3e0008ff9a3924bad7e5bc16bc4"
        autoupdate.strategy = "latest_github_tag"

        [resources.sources.ui-library]
        url = "https://github.com/pkp/ui-library/archive/refs/tags/3_4_0-7.tar.gz"
        sha256 = "4208baa4df7bcc0c38e4a14d17cd27f2ea1bc852cd07348d181f52c44d93b743"
        autoupdate.strategy = "latest_github_tag"

        [resources.sources.citationStyleLanguage]
        url = "https://github.com/pkp/citationStyleLanguage/archive/refs/tags/3_4_0-7.tar.gz"
        sha256 = "03f4e7f15b56f5e83554a78eb73d5fc6cca3b5b0eb3ebdf33125edf36e78d535"
        autoupdate.strategy = "latest_github_tag"

        [resources.sources.COUNTER]
        url = "https://github.com/pkp/COUNTER/archive/refs/heads/main.zip"
        sha256 = "a69d7d8e7c1eb12e92db32402cb67b321776000899d925bb22c0d7dbcb6ac3b8"
        autoupdate.strategy = "latest_github_tag"

        [resources.sources.browse]
        url = "https://github.com/pkp/browse/archive/refs/tags/3_4_0-7.tar.gz"
        sha256 = "a6fcc04acb55b35ef631c319a18b2e00c3e736a630d03218f3415c05fef44ddb"
        autoupdate.strategy = "latest_github_tag"

        [resources.sources.googleScholar]
        url = "https://github.com/pkp/googleScholar/archive/refs/tags/3_4_0-7.tar.gz"
        sha256 = "117b502c37b44b709cce17f64eb048cd3d8af47f6fa21b0216734c9171e5dad3"
        autoupdate.strategy = "latest_github_tag"

        [resources.sources.crossref]
        url = "https://github.com/pkp/crossref-ojs/archive/refs/tags/3_4_0-7.tar.gz"
        sha256 = "a7fd22be4dc2e484fc3922ab46acccf9b9c554e058ba1db4731e7f4f4fc35fdb"
        autoupdate.strategy = "latest_github_tag"

        [resources.sources.webFeed]
        url = "https://github.com/pkp/webFeed/archive/refs/tags/3_4_0-7.tar.gz"
        sha256 = "c4a79c10cd79b8329dd20a3d10c595c4f38efdaad3f3e3e195db89145826e70a"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server, php8.3-mysqli, php8.3-mbstring, php8.3-xml, php8.3-intl"

    [resources.database]
    type = "mysql"
