#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

ynh_replace_string --match_string="__OLD_DOMAIN____OLD_PATH__" --replace_string="__NEW_DOMAIN____NEW_PATH__" --target_file="$install_dir/config.inc.php"

chmod 600 "$install_dir/config.inc.php"
chown "$app:$app" "$install_dir/config.inc.php"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
