#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

ynh_config_add --template="config.inc.php" --destination="$install_dir/config.inc.php"
ynh_replace --match="installed = Off" --replace="installed = On" --file="$install_dir/config.inc.php"
ynh_store_file_checksum "$install_dir/config.inc.php"
chmod 600 "$install_dir/config.inc.php"
chown "$app:$app" "$install_dir/config.inc.php"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
