#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

salt=$(ynh_string_random --length=32)
api_key_secret=$(ynh_string_random --length=32)
app_key=$(ynh_string_random --length=32)

ynh_app_setting_set --key=salt --value=$salt
ynh_app_setting_set --key=api_key_secret --value=$api_key_secret
ynh_app_setting_set --key=app_key --value=$app_key
ynh_app_setting_set --key=language --value=$language
ynh_app_setting_set --key=locale --value=$locale

admin_mail=$(ynh_user_get_info --username=$admin --key=mail)

timezone="$(timedatectl show --value --property=Timezone)"
ynh_app_setting_set --key=timezone --value=$timezone

timezone_formatted=$(format_timezone "$timezone")

ynh_app_setting_set_default --key=mail_user --value="noreply"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding app's configuration file..."

# Remove trailing slash
path="${path%/}"

ynh_config_add --template="config.inc.php" --destination="$install_dir/config.inc.php"

chmod 600 "$install_dir/config.inc.php"
chown "$app:www-data" "$install_dir/config.inc.php"

ynh_config_add --template=".cron" --destination="/etc/cron.d/$app"

chown -R $app:www-data "$install_dir"

ynh_script_progression "Installing $app..."

pushd "$install_dir"

expect <<EOF
spawn php tools/install.php
expect "Language*" { send "$language\r" }
expect "Locale*" { send "$locale\r" }
expect "File directory*" { send "$data_dir\r" }
expect "Administrator username*" { send "$admin\r" }
expect "Administrator password*" { send "$password\r" }
expect "Repeat password*" { send "$password\r" }
expect "Administrator email*" { send "$admin_mail\r" }
expect "Database driver*" { send "mysqli\r" }
expect "Database host*" { send "localhost\r" }
expect "Database username*" { send "$db_user\r" }
expect "Database password*" { send "$db_pwd\r" }
expect "Database name*" { send "$db_name\r" }
expect "OAI repository identifier*" { send "$domain\r" }
expect "Create database tables?*" { send "y\r" }
expect "Install sample data?*" { send "y\r" }
expect eof
EOF

popd


ynh_store_file_checksum "$install_dir/config.inc.php"
 
#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
