#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

salt=$(ynh_string_random --length=32)
api_key_secret=$(ynh_string_random --length=32)
app_key=$(ynh_string_random --length=32)

ynh_app_setting_set --key=salt --value=$salt
ynh_app_setting_set --key=api_key_secret --value=$api_key_secret
ynh_app_setting_set --key=app_key --value=$app_key
ynh_app_setting_set --key=language --value=$language
ynh_app_setting_set --key=locale --value=$locale

admin_mail=$(ynh_user_get_info --username=$admin --key=mail)

timezone="$(cat /etc/timezone)"
ynh_app_setting_set --key=timezone --value=$timezone

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding app's configuration file..."

ynh_config_add --template="config.inc.php" --destination="$install_dir/config.inc.php"

chmod 600 "$install_dir/config.inc.php"
chown "$app:$app" "$install_dir/config.inc.php"

ynh_config_add --template=".cron" --destination="/etc/cron.d/$app"

# Running the install using curl
# curl -X POST -d "installLanguage=$language" -d "adminUsername=$admin" -d "adminPassword=$password" -d "adminPassword2=$password" -d "adminEmail=$admin_mail" -d "locale=$locale" -d "timeZone=$timezone" -d "filesDir=$data_dir" -d "databaseDriver=mysqli" -d "databaseHost=localhost" -d "databaseUsername=$db_user" -d "databasePassword=$db_pwd" -d "databaseName=$db_name" -d "oaiRepositoryId=ojs.local" -d "submitFormButton=1" -i $domain$path/index.php/index/install/install  -v

ynh_local_curl "$domain$path/index.php/index/install/install" "installLanguage=$language" "adminUsername=$admin" "adminPassword=$password" "adminPassword2=$password" "adminEmail=$admin_mail" "locale=$locale" "timeZone=$timezone" "filesDir=$data_dir" "databaseDriver=mysqli" "databaseHost=localhost" "databaseUsername=$db_user" "databasePassword=$db_pwd" "databaseName=$db_name" "oaiRepositoryId=ojs.local" "submitFormButton=1"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
