#!/bin/bash
### App file generated with YoloGen, the Yunohost app generator, version .

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================
source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
# REMOVE SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Removing system configurations related to $app..."

ynh_remove_nginx_config

ynh_remove_fpm_config

ynh_remove_logrotate

ynh_remove_fail2ban_config

# Remove other various files specific to the app... such as :

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed" --last
