#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================

#ynh_app_setting_set_default --key=mail_user‎ --value=noreply

if [[ "${mail_user:-}" != "noreply" && "${mail_user:-}" != "contact" ]]; then
    mail_user="noreply"
    ynh_app_setting_set --key=mail_user --value="noreply" 
fi

salt=$(ynh_app_setting_get --app=$app --key=salt)
api_key_secret=$(ynh_app_setting_get --app=$app --key=api_key_secret)
app_key=$(ynh_app_setting_get --app=$app --key=app_key)
language=$(ynh_app_setting_get --app=$app --key=language)
timezone=$(ynh_app_setting_get --app=$app --key=timezone)

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace --keep="config.inc.php public"

ynh_config_add --template="config.inc.php" --destination="$install_dir/config.inc.php"

ynh_replace --match="installed = Off" --replace="installed = On" --file="$install_dir/config.inc.php"

ynh_store_file_checksum "$install_dir/config.inc.php"

chown -R "$app:www-data" "$install_dir"

pushd $install_dir
  php8.4 tools/upgrade.php check
  php8.4 -d memory_limit=2048M tools/upgrade.php upgrade
popd

chown -R "$app:www-data" "$install_dir"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

ynh_config_add --template=".cron" --destination="/etc/cron.d/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
