#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================

#ynh_app_setting_set_default --key=mail_user‎ --value=noreply

if [[ "$mail_user" != "noreply" && "$mail_user" != "contact" ]]; then
    mail_user="noreply"
    ynh_app_setting_set --key=mail_user --value="noreply" 
fi

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace --keep="config.inc.php public locale plugins"

pushd $install_dir
  php8.4 tools/upgrade.php check
  php8.4 -d memory_limit=2048M tools/upgrade.php upgrade
popd

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

ynh_config_add --template=".cron" --destination="/etc/cron.d/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
